name: CI/CD (master)

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/pierreluc46/junia-2025
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_PLATFORMS: linux/amd64

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Lint PHP (exclut ./useless/)
        run: |
          set -euo pipefail
          mapfile -d '' FILES < <(find . -path './useless' -prune -o -type f -name '*.php' -print0)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "Aucun fichier PHP trouvé."; exit 0
          fi
          for f in "${FILES[@]}"; do
            echo "Lint: $f"
            php -l "$f"
          done

  build:
    runs-on: self-hosted
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:master

  push:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:master

  deploy:
    runs-on: self-hosted
    needs: [push]
    steps:
      - uses: actions/checkout@v4

      # 1) Vérifie que les secrets existent (message clair sinon)
      - name: Check SSH secrets
        run: |
          [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] || { echo "::error::Missing SSH_PRIVATE_KEY"; exit 1; }
          [ -n "${{ secrets.SSH_HOST }}" ] || { echo "::error::Missing SSH_HOST"; exit 1; }
          [ -n "${{ secrets.SSH_USER }}" ] || { echo "::error::Missing SSH_USER"; exit 1; }

      # 2) Écrit la clé privée dans un fichier
      - name: Write SSH private key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      # 3) known_hosts
      - name: known_hosts
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            printf "%s\n" "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          else
            ssh-keyscan -t rsa "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          fi
          chmod 644 ~/.ssh/known_hosts

      # 4) Déploiement sans sudo, port 8080, /usr/bin/docker explicit
      - name: Remote deploy (no sudo, /usr/bin/docker, port 8080)
        env:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes "${REMOTE_USER}@${REMOTE_HOST}" \
            GHCR_USER="${GHCR_USER}" GHCR_TOKEN="${GHCR_TOKEN}" IMAGE_NAME="${IMAGE_NAME}" IMAGE_TAG="${IMAGE_TAG}" 'bash -s' << 'EOF'
          set -euo pipefail
          set -x

          unalias docker 2>/dev/null || true
          DOCKER_BIN="/usr/bin/docker"
          if ! [ -x "$DOCKER_BIN" ]; then
            DOCKER_BIN="$(command -v docker)"
          fi

          if [ -n "${GHCR_TOKEN:-}" ]; then
            echo "${GHCR_TOKEN}" | "$DOCKER_BIN" login ghcr.io -u "${GHCR_USER}" --password-stdin || true
          fi

          "$DOCKER_BIN" pull "${IMAGE_NAME}:${IMAGE_TAG}" || "$DOCKER_BIN" pull "${IMAGE_NAME}:master"
          "$DOCKER_BIN" rm -f webapp 2>/dev/null || true
          "$DOCKER_BIN" run -d --name webapp -p 8080:80 "${IMAGE_NAME}:${IMAGE_TAG}"
          "$DOCKER_BIN" image prune -f || true
          EOF
